### PR TITLE
[Feature] Add .editorconfig file

### PR DESCRIPTION
**Pull request by ErickZH**
Add `.editorconfig` file

### CODE REVIEW

**Comment by calebporzio** [comment]
Change that indent size to 4, get rid of the `.yml` config, and you got yourself a deal!

Thanks for contributing!

**Comment by ErickZH** [comment]
@calebporzio Yeah!!

**Comment by calebporzio** [comment]
@ErickZH - there are a lot more changes in this PR than before (I think, unless I didn't see them before). Let's keep this to just the .editorconfig file. Thanks! (I'm open to your styling fixes, just want to keep PRs focused.)

**Comment by ErickZH** [comment]
@calebporzio Okay, I'll just keep the changes in the `editorconfig` file 😅

**Pull request closed without merging**
